---
# tasks file for lamp2
- name: LAMP installation
  include_vars: '{{ansible_os_family}}.yml'


- name: Debian/Ubuntu
  apt: name={{item}} state=present
  with_items: '{{lamp_packages}}'
  when: ansible_os_family == "Debian"
  notify:
    - starting and enabling apache
    - starting and enabling mariadb

- name: Centos/RedHat
  yum: name={{item}} state=present
  with_items: '{{lamp_packages}}'
  when: ansible_os_family == "RedHat"
  notify:
    - starting and enabling apache
    - starting and enabling mariadb

- name: ouverture de port
  shell: firewall-cmd --zone=public --permanent --add-service=http --add-service=https && firewall-cmd --reload
  when: ansible_os_family == "RedHat"

- name: Mise à jour de index.html
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html
    backup: yes
    owner: '{{apache_user}}'
    group: '{{apache_user}}'
    mode: 0644
